enum TokenType {
    STR, WHITESPACE, NEWLINE,
    H1, H2, H3, H4, H5, H6,
    MINUS, EQ, PLUS, SEMICOLON, BANG, PIPE,
    ASTERISK, UNDERSCORE,
    DOUBLE_ASTERISK, DOUBLE_UNDERSCORE, DOUBLE_TILDE,
    LIST_NUMBER,
    LT, GT,
    LEFT_SQ_PAR, RIGHT_SQ_PAR,
    LEFT_PAR, RIGHT_PAR,
    BACKTICK, TRIPLE_BACKTICK
}

export default TokenType;
